"""CRM card callback handlers for quick actions (#697 Task 8).

Router for crm:* inline keyboard callbacks generated by crm_cards.py:
- crm:lead:note:{id}    → quick note to lead (FSM TextInput → add_note)
- crm:lead:task:{id}    → quick task for lead (FSM TextInput → create_task)
- crm:task:complete:{id} → complete task immediately (complete_task)
- crm:task:postpone:{id} → postpone task by +1 day (update_task)
- crm:contact:note:{id} → quick note to contact (FSM TextInput → add_note)
"""

from __future__ import annotations

import datetime
import logging
import time
from typing import Any

from aiogram import F, Router
from aiogram.filters import StateFilter
from aiogram.fsm.context import FSMContext
from aiogram.types import CallbackQuery, InaccessibleMessage, Message

from telegram_bot.dialogs.states import CrmQuickActionSG
from telegram_bot.services.kommo_models import TaskCreate, TaskUpdate


logger = logging.getLogger(__name__)

_NOTE_PROMPT = "✏️ Введите текст заметки:"
_TASK_PROMPT = "✅ Введите текст задачи:"
_NOTE_SUCCESS = "✅ Заметка добавлена."
_TASK_SUCCESS = "✅ Задача создана."
_NO_CRM = "⚠️ CRM недоступна."


async def on_lead_note(
    callback: CallbackQuery,
    state: FSMContext,
    kommo_client: Any | None = None,
) -> None:
    """Handle crm:lead:note:{id} — start quick note FSM for a lead."""
    if kommo_client is None:
        await callback.answer(_NO_CRM, show_alert=True)
        return
    # callback.data is guaranteed non-None by F.data.regexp filter
    assert callback.data is not None
    # callback.data format: crm:lead:note:{id}
    lead_id = int(callback.data.split(":")[3])
    await state.set_state(CrmQuickActionSG.waiting_note)
    await state.update_data(entity_type="leads", entity_id=lead_id)
    if callback.message and not isinstance(callback.message, InaccessibleMessage):
        await callback.message.answer(_NOTE_PROMPT)
    await callback.answer()


async def on_lead_task(
    callback: CallbackQuery,
    state: FSMContext,
    kommo_client: Any | None = None,
) -> None:
    """Handle crm:lead:task:{id} — start quick task FSM for a lead."""
    if kommo_client is None:
        await callback.answer(_NO_CRM, show_alert=True)
        return
    # callback.data is guaranteed non-None by F.data.regexp filter
    assert callback.data is not None
    # callback.data format: crm:lead:task:{id}
    lead_id = int(callback.data.split(":")[3])
    await state.set_state(CrmQuickActionSG.waiting_task)
    await state.update_data(entity_id=lead_id, entity_type="leads")
    if callback.message and not isinstance(callback.message, InaccessibleMessage):
        await callback.message.answer(_TASK_PROMPT)
    await callback.answer()


async def on_task_complete(
    callback: CallbackQuery,
    kommo_client: Any | None = None,
) -> None:
    """Handle crm:task:complete:{id} — complete task immediately."""
    if kommo_client is None:
        await callback.answer(_NO_CRM, show_alert=True)
        return
    # callback.data is guaranteed non-None by F.data.regexp filter
    assert callback.data is not None
    # callback.data format: crm:task:complete:{id}
    task_id = int(callback.data.split(":")[3])
    try:
        await kommo_client.complete_task(task_id)
        await callback.answer("✅ Задача завершена.")
        if callback.message and not isinstance(callback.message, InaccessibleMessage):
            await callback.message.edit_text("✅ Задача завершена.")
    except Exception:
        logger.exception("Failed to complete task %d", task_id)
        await callback.answer("⚠️ Ошибка при завершении задачи.", show_alert=True)


async def on_task_postpone(
    callback: CallbackQuery,
    kommo_client: Any | None = None,
) -> None:
    """Handle crm:task:postpone:{id} — postpone task by +1 day."""
    if kommo_client is None:
        await callback.answer(_NO_CRM, show_alert=True)
        return
    # callback.data is guaranteed non-None by F.data.regexp filter
    assert callback.data is not None
    # callback.data format: crm:task:postpone:{id}
    task_id = int(callback.data.split(":")[3])
    due_ts = int(time.time()) + 86400
    try:
        await kommo_client.update_task(task_id, TaskUpdate(complete_till=due_ts))
        due_dt = datetime.datetime.fromtimestamp(due_ts, tz=datetime.UTC).strftime("%d.%m.%Y")
        msg = f"⏰ Задача отложена до {due_dt}."
        await callback.answer(msg)
        if callback.message and not isinstance(callback.message, InaccessibleMessage):
            await callback.message.edit_text(msg)
    except Exception:
        logger.exception("Failed to postpone task %d", task_id)
        await callback.answer("⚠️ Ошибка при откладывании задачи.", show_alert=True)


async def on_contact_note(
    callback: CallbackQuery,
    state: FSMContext,
    kommo_client: Any | None = None,
) -> None:
    """Handle crm:contact:note:{id} — start quick note FSM for a contact."""
    if kommo_client is None:
        await callback.answer(_NO_CRM, show_alert=True)
        return
    # callback.data is guaranteed non-None by F.data.regexp filter
    assert callback.data is not None
    # callback.data format: crm:contact:note:{id}
    contact_id = int(callback.data.split(":")[3])
    await state.set_state(CrmQuickActionSG.waiting_note)
    await state.update_data(entity_type="contacts", entity_id=contact_id)
    if callback.message and not isinstance(callback.message, InaccessibleMessage):
        await callback.message.answer(_NOTE_PROMPT)
    await callback.answer()


async def on_note_text_received(
    message: Message,
    state: FSMContext,
    kommo_client: Any | None = None,
) -> None:
    """Handle text input in CrmQuickActionSG.waiting_note state."""
    data = await state.get_data()
    entity_type: str = data.get("entity_type", "leads")
    entity_id: int = data.get("entity_id", 0)
    text = (message.text or "").strip()

    await state.clear()

    if not text:
        await message.answer("⚠️ Текст заметки не может быть пустым.")
        return

    if kommo_client is None:
        await message.answer(_NO_CRM)
        return

    try:
        await kommo_client.add_note(entity_type, entity_id, text)
        await message.answer(_NOTE_SUCCESS)
    except Exception:
        logger.exception("Failed to add note for %s #%d", entity_type, entity_id)
        await message.answer("⚠️ Ошибка при добавлении заметки.")


async def on_task_text_received(
    message: Message,
    state: FSMContext,
    kommo_client: Any | None = None,
) -> None:
    """Handle text input in CrmQuickActionSG.waiting_task state."""
    data = await state.get_data()
    entity_id: int = data.get("entity_id", 0)
    text = (message.text or "").strip()

    await state.clear()

    if not text:
        await message.answer("⚠️ Текст задачи не может быть пустым.")
        return

    if kommo_client is None:
        await message.answer(_NO_CRM)
        return

    try:
        due_ts = int(time.time()) + 86400
        await kommo_client.create_task(
            TaskCreate(text=text, entity_id=entity_id, complete_till=due_ts)
        )
        await message.answer(_TASK_SUCCESS)
    except Exception:
        logger.exception("Failed to create task for lead #%d", entity_id)
        await message.answer("⚠️ Ошибка при создании задачи.")


def create_crm_router() -> Router:
    """Create router with CRM card action handlers."""
    router = Router(name="crm_callbacks")

    # Immediate actions (no FSM required)
    router.callback_query(F.data.regexp(r"^crm:task:complete:\d+$"))(on_task_complete)
    router.callback_query(F.data.regexp(r"^crm:task:postpone:\d+$"))(on_task_postpone)

    # FSM-triggering actions
    router.callback_query(F.data.regexp(r"^crm:lead:note:\d+$"))(on_lead_note)
    router.callback_query(F.data.regexp(r"^crm:lead:task:\d+$"))(on_lead_task)
    router.callback_query(F.data.regexp(r"^crm:contact:note:\d+$"))(on_contact_note)

    # FSM text input handlers
    router.message(StateFilter(CrmQuickActionSG.waiting_note), F.text)(on_note_text_received)
    router.message(StateFilter(CrmQuickActionSG.waiting_task), F.text)(on_task_text_received)

    return router
