"""CRM card callback handlers for quick actions (#697 Task 8).

Router for crm:* inline keyboard callbacks generated by crm_cards.py:
- crm:lead:note:{id}    → quick note to lead (FSM TextInput → add_note)
- crm:lead:task:{id}    → quick task for lead (FSM TextInput → create_task)
- crm:task:complete:{id} → complete task immediately (complete_task)
- crm:task:postpone:{id} → postpone task by +1 day (update_task)
- crm:contact:note:{id} → quick note to contact (FSM TextInput → add_note)
"""

from __future__ import annotations

import datetime
import logging
import time
from typing import Any

from aiogram import F, Router
from aiogram.filters import StateFilter
from aiogram.fsm.context import FSMContext
from aiogram.types import CallbackQuery, InaccessibleMessage, Message

from telegram_bot.callback_data import CrmActionCB
from telegram_bot.dialogs.states import CrmQuickActionSG
from telegram_bot.services.kommo_models import TaskCreate, TaskUpdate


logger = logging.getLogger(__name__)

_NOTE_PROMPT = "✏️ Введите текст заметки:"
_TASK_PROMPT = "✅ Введите текст задачи:"
_NOTE_SUCCESS = "✅ Заметка добавлена."
_TASK_SUCCESS = "✅ Задача создана."
_NO_CRM = "⚠️ CRM недоступна."


async def on_lead_note(
    callback: CallbackQuery,
    state: FSMContext,
    callback_data: CrmActionCB | None = None,
    kommo_client: Any | None = None,
) -> None:
    """Handle crm:lead:note:{id} — start quick note FSM for a lead."""
    if kommo_client is None:
        await callback.answer(_NO_CRM, show_alert=True)
        return
    if callback_data is not None:
        lead_id = callback_data.entity_id
    else:
        assert callback.data is not None
        lead_id = int(callback.data.split(":")[3])
    await state.set_state(CrmQuickActionSG.waiting_note)
    await state.update_data(entity_type="leads", entity_id=lead_id)
    if callback.message and not isinstance(callback.message, InaccessibleMessage):
        await callback.message.answer(_NOTE_PROMPT)
    await callback.answer()


async def on_lead_task(
    callback: CallbackQuery,
    state: FSMContext,
    callback_data: CrmActionCB | None = None,
    kommo_client: Any | None = None,
) -> None:
    """Handle crm:lead:task:{id} — start quick task FSM for a lead."""
    if kommo_client is None:
        await callback.answer(_NO_CRM, show_alert=True)
        return
    if callback_data is not None:
        lead_id = callback_data.entity_id
    else:
        assert callback.data is not None
        lead_id = int(callback.data.split(":")[3])
    await state.set_state(CrmQuickActionSG.waiting_task)
    await state.update_data(entity_id=lead_id, entity_type="leads")
    if callback.message and not isinstance(callback.message, InaccessibleMessage):
        await callback.message.answer(_TASK_PROMPT)
    await callback.answer()


async def on_task_complete(
    callback: CallbackQuery,
    callback_data: CrmActionCB | None = None,
    kommo_client: Any | None = None,
) -> None:
    """Handle crm:task:complete:{id} — complete task immediately."""
    if kommo_client is None:
        await callback.answer(_NO_CRM, show_alert=True)
        return
    if callback_data is not None:
        task_id = callback_data.entity_id
    else:
        assert callback.data is not None
        task_id = int(callback.data.split(":")[3])
    try:
        await kommo_client.complete_task(task_id)
        await callback.answer("✅ Задача завершена.")
        if callback.message and not isinstance(callback.message, InaccessibleMessage):
            await callback.message.edit_text("✅ Задача завершена.")
    except Exception:
        logger.exception("Failed to complete task %d", task_id)
        await callback.answer("⚠️ Ошибка при завершении задачи.", show_alert=True)


async def on_task_postpone(
    callback: CallbackQuery,
    callback_data: CrmActionCB | None = None,
    kommo_client: Any | None = None,
) -> None:
    """Handle crm:task:postpone:{id} — postpone task by +1 day."""
    if kommo_client is None:
        await callback.answer(_NO_CRM, show_alert=True)
        return
    if callback_data is not None:
        task_id = callback_data.entity_id
    else:
        assert callback.data is not None
        task_id = int(callback.data.split(":")[3])
    due_ts = int(time.time()) + 86400
    try:
        await kommo_client.update_task(task_id, TaskUpdate(complete_till=due_ts))
        due_dt = datetime.datetime.fromtimestamp(due_ts, tz=datetime.UTC).strftime("%d.%m.%Y")
        msg = f"⏰ Задача отложена до {due_dt}."
        await callback.answer(msg)
        if callback.message and not isinstance(callback.message, InaccessibleMessage):
            await callback.message.edit_text(msg)
    except Exception:
        logger.exception("Failed to postpone task %d", task_id)
        await callback.answer("⚠️ Ошибка при откладывании задачи.", show_alert=True)


async def on_contact_note(
    callback: CallbackQuery,
    state: FSMContext,
    callback_data: CrmActionCB | None = None,
    kommo_client: Any | None = None,
) -> None:
    """Handle crm:contact:note:{id} — start quick note FSM for a contact."""
    if kommo_client is None:
        await callback.answer(_NO_CRM, show_alert=True)
        return
    if callback_data is not None:
        contact_id = callback_data.entity_id
    else:
        assert callback.data is not None
        contact_id = int(callback.data.split(":")[3])
    await state.set_state(CrmQuickActionSG.waiting_note)
    await state.update_data(entity_type="contacts", entity_id=contact_id)
    if callback.message and not isinstance(callback.message, InaccessibleMessage):
        await callback.message.answer(_NOTE_PROMPT)
    await callback.answer()


async def on_note_text_received(
    message: Message,
    state: FSMContext,
    kommo_client: Any | None = None,
) -> None:
    """Handle text input in CrmQuickActionSG.waiting_note state."""
    data = await state.get_data()
    entity_type: str = data.get("entity_type", "leads")
    entity_id: int = data.get("entity_id", 0)
    text = (message.text or "").strip()

    await state.clear()

    if not text:
        await message.answer("⚠️ Текст заметки не может быть пустым.")
        return

    if kommo_client is None:
        await message.answer(_NO_CRM)
        return

    try:
        await kommo_client.add_note(entity_type, entity_id, text)
        await message.answer(_NOTE_SUCCESS)
    except Exception:
        logger.exception("Failed to add note for %s #%d", entity_type, entity_id)
        await message.answer("⚠️ Ошибка при добавлении заметки.")


async def on_task_text_received(
    message: Message,
    state: FSMContext,
    kommo_client: Any | None = None,
) -> None:
    """Handle text input in CrmQuickActionSG.waiting_task state."""
    data = await state.get_data()
    entity_id: int = data.get("entity_id", 0)
    text = (message.text or "").strip()

    await state.clear()

    if not text:
        await message.answer("⚠️ Текст задачи не может быть пустым.")
        return

    if kommo_client is None:
        await message.answer(_NO_CRM)
        return

    try:
        due_ts = int(time.time()) + 86400
        await kommo_client.create_task(
            TaskCreate(text=text, entity_id=entity_id, complete_till=due_ts)
        )
        await message.answer(_TASK_SUCCESS)
    except Exception:
        logger.exception("Failed to create task for lead #%d", entity_id)
        await message.answer("⚠️ Ошибка при создании задачи.")


_EDIT_FIELD_PROMPT = "✏️ Что изменить?\n\n1️⃣ Текст задачи\n2️⃣ Срок выполнения\n\nОтправьте 1 или 2:"
_EDIT_TEXT_PROMPT = "📝 Введите новый текст задачи:"
_EDIT_DATE_PROMPT = "📅 Введите новый срок (ДД.ММ.ГГГГ ЧЧ:ММ):"
_EDIT_SUCCESS = "✅ Задача обновлена."


async def on_task_edit(
    callback: CallbackQuery,
    state: FSMContext,
    callback_data: CrmActionCB | None = None,
    kommo_client: Any | None = None,
) -> None:
    """Handle crm:task:edit:{id} — start edit field choice FSM."""
    if kommo_client is None:
        await callback.answer(_NO_CRM, show_alert=True)
        return
    if callback_data is not None:
        task_id = callback_data.entity_id
    else:
        assert callback.data is not None
        task_id = int(callback.data.split(":")[3])
    await state.set_state(CrmQuickActionSG.edit_task_choose_field)
    await state.update_data(edit_task_id=task_id)
    if callback.message and not isinstance(callback.message, InaccessibleMessage):
        await callback.message.answer(_EDIT_FIELD_PROMPT)
    await callback.answer()


async def on_edit_field_chosen(
    message: Message,
    state: FSMContext,
    kommo_client: Any | None = None,
) -> None:
    """Handle field choice: 1=text, 2=date."""
    choice = (message.text or "").strip()
    if choice == "1":
        await state.set_state(CrmQuickActionSG.edit_task_text)
        await message.answer(_EDIT_TEXT_PROMPT)
    elif choice == "2":
        await state.set_state(CrmQuickActionSG.edit_task_date)
        await message.answer(_EDIT_DATE_PROMPT)
    else:
        await message.answer("⚠️ Отправьте 1 или 2.")


async def on_edit_task_text_received(
    message: Message,
    state: FSMContext,
    kommo_client: Any | None = None,
) -> None:
    """Handle new task text input."""
    data = await state.get_data()
    task_id = data.get("edit_task_id", 0)
    text = (message.text or "").strip()

    if not text:
        await message.answer("⚠️ Текст не может быть пустым.")
        return
    if kommo_client is None:
        await state.clear()
        await message.answer(_NO_CRM)
        return

    try:
        await kommo_client.update_task(task_id, TaskUpdate(text=text))
        await state.clear()
        await message.answer(_EDIT_SUCCESS)
    except Exception:
        logger.exception("Failed to update task %d text", task_id)
        await state.clear()
        await message.answer("⚠️ Ошибка при обновлении задачи.")


async def on_edit_task_date_received(
    message: Message,
    state: FSMContext,
    kommo_client: Any | None = None,
) -> None:
    """Handle new task due date input (DD.MM.YYYY HH:MM)."""
    data = await state.get_data()
    task_id = data.get("edit_task_id", 0)
    raw = (message.text or "").strip()

    if kommo_client is None:
        await state.clear()
        await message.answer(_NO_CRM)
        return

    try:
        dt = datetime.datetime.strptime(raw, "%d.%m.%Y %H:%M")
        dt = dt.replace(tzinfo=datetime.UTC)
        due_ts = int(dt.timestamp())
    except ValueError:
        await message.answer("⚠️ Неверный формат. Используйте: ДД.ММ.ГГГГ ЧЧ:ММ")
        return

    try:
        await kommo_client.update_task(task_id, TaskUpdate(complete_till=due_ts))
        await state.clear()
        await message.answer(_EDIT_SUCCESS)
    except Exception:
        logger.exception("Failed to update task %d due date", task_id)
        await state.clear()
        await message.answer("⚠️ Ошибка при обновлении задачи.")


def create_crm_router() -> Router:
    """Create router with CRM card action handlers."""
    router = Router(name="crm_callbacks")

    # Immediate actions (no FSM required)
    router.callback_query(CrmActionCB.filter((F.entity == "task") & (F.action == "complete")))(
        on_task_complete
    )
    router.callback_query(CrmActionCB.filter((F.entity == "task") & (F.action == "postpone")))(
        on_task_postpone
    )

    # FSM-triggering actions
    router.callback_query(CrmActionCB.filter((F.entity == "lead") & (F.action == "note")))(
        on_lead_note
    )
    router.callback_query(CrmActionCB.filter((F.entity == "lead") & (F.action == "task")))(
        on_lead_task
    )
    router.callback_query(CrmActionCB.filter((F.entity == "contact") & (F.action == "note")))(
        on_contact_note
    )

    # FSM text input handlers
    router.message(StateFilter(CrmQuickActionSG.waiting_note), F.text)(on_note_text_received)
    router.message(StateFilter(CrmQuickActionSG.waiting_task), F.text)(on_task_text_received)

    # Task edit FSM
    router.callback_query(CrmActionCB.filter((F.entity == "task") & (F.action == "edit")))(
        on_task_edit
    )
    router.message(StateFilter(CrmQuickActionSG.edit_task_choose_field), F.text)(
        on_edit_field_chosen
    )
    router.message(StateFilter(CrmQuickActionSG.edit_task_text), F.text)(on_edit_task_text_received)
    router.message(StateFilter(CrmQuickActionSG.edit_task_date), F.text)(on_edit_task_date_received)

    return router
