# Gitleaks configuration
# https://github.com/gitleaks/gitleaks

title = "Gitleaks config"

[allowlist]
  description = "Global allowlist"
  paths = [
    '''\.venv/''',
    '''node_modules/''',
    '''uv.lock''',
    '''package-lock\.json''',
    '''\.git/''',
    '''tests/''',
    '''scripts/''',
    '''docs/''',
    '''\.env\.example''',
  ]
