"""Domain-specific defaults for the current real-estate implementation.

All constants in this module are domain-specific (Bulgarian real-estate /
apartment catalog). They are collected here so the generic runtime modules
(query_filter_signal, query_preprocessor, classify, rag_core, generation)
import from one place rather than embedding domain strings inline.

To adapt the system to a different domain, replace the values in this file
(city patterns, transliteration map, canned responses, prompts) without
touching generic runtime logic.

Issue: #2949 — isolate domain logic from generic runtime.
"""

from __future__ import annotations

import re


# ---------------------------------------------------------------------------
# Demo catalog domain: canonical cities, complexes, golden queries (#3203)
#
# These are the single source of truth shared by the seed data
# (data/apartments.csv, generated by scripts/apartments/generate_seed.py),
# the extraction schema (src/models/apartment.py HardFilters), and the
# visible demo prompts (telegram_bot/keyboards/demo_keyboard.py).
# Every advertised query must be answerable from the shipped seed through
# the production filter path.
# ---------------------------------------------------------------------------

#: Cities present in the demo seed. Offered verbatim by filter UIs and
#: accepted verbatim by ``HardFilters.city``.
DEMO_CITIES: tuple[str, ...] = ("Солнечный берег", "Свети Влас", "Элените")

#: Demo complexes mapped to their demo city. The seed contains listings for
#: every complex here; filter UIs and the extractor describe exactly these.
DEMO_COMPLEX_CITIES: dict[str, str] = {
    "Premier Fort Beach": "Солнечный берег",
    "Prestige Fort Beach": "Солнечный берег",
    "Nessebar Fort Residence": "Солнечный берег",
    "Green Fort Suites": "Солнечный берег",
    "Panorama Fort Beach": "Элените",
    "Marina View Fort Beach": "Элените",
    "Messambria Fort Beach": "Элените",
    "Premier Fort Suites": "Свети Влас",
    "Crown Fort Club": "Свети Влас",
    "Imperial Fort Club": "Свети Влас",
}

#: Prepositional prompt forms ("в …") for demo cities. Used by dynamic example
#: generation so visible queries stay grammatical and extract back to the
#: canonical city via the regex extractor aliases.
DEMO_CITY_PROMPT_FORMS: dict[str, str] = {
    "Солнечный берег": "в Солнечном берегу",
    "Свети Влас": "в Свети Власе",
    "Элените": "в Элените",
}

#: Golden demo queries: each must return at least GOLDEN_QUERY_MIN_RESULTS
#: listings from the shipped seed through the production extraction path
#: (regex extractor → HardFilters → Qdrant filter). The demo keyboard shows
#: these verbatim.
GOLDEN_DEMO_QUERIES: tuple[str, ...] = (
    "Студия в Солнечном берегу до 100 000€",
    "Двушка в Premier Fort Beach",
    "Трёшка в Элените до 200 000€",
    "Апартамент в Свети Влас от 150 000€",
)

#: Intentional no-result demo query: valid filters whose combination is
#: deliberately absent from the seed. Exercises the empty-state recovery copy.
NO_RESULT_DEMO_QUERY: str = "Трёшка в Свети Власе до 60 000€"

#: Minimum listings every golden query must return from the seed.
GOLDEN_QUERY_MIN_RESULTS: int = 3


# ---------------------------------------------------------------------------
# City / location detection (Bulgarian Black Sea + Sofia)
# ---------------------------------------------------------------------------

_CITY_RE = re.compile(
    r"\b("
    r"несеб\w*"
    r"|варн\w*"
    r"|бургас\w*"
    r"|солнечн\w*\s+берег\w*"
    r"|свети\s+влас\w*"
    r"|свят\w+\s+влас\w*"
    r"|эленит\w*"
    r"|помори\w*"
    r"|созопол\w*"
    r"|софи\w*"
    r")\b",
    re.IGNORECASE,
)

# ---------------------------------------------------------------------------
# Transliteration map: Latin → Cyrillic (Bulgarian cities and resorts)
# ---------------------------------------------------------------------------

TRANSLIT_MAP: dict[str, str] = {
    # Cities
    "Burgas": "Бургас",
    "Varna": "Варна",
    "Sofia": "София",
    "Plovdiv": "Пловдив",
    # Resorts
    "Nesebar": "Несебър",
    "Nessebar": "Несебър",
    "Sozopol": "Созопол",
    "Pomorie": "Поморие",
    "Sunny Beach": "Солнечный берег",
    "Sveti Vlas": "Святой Влас",
    "Svyati Vlas": "Святой Влас",
    "St Vlas": "Святой Влас",
    "Elenite": "Елените",
    "Ravda": "Равда",
    "Sarafovo": "Сарафово",
    "Primorsko": "Приморско",
    "Tsarevo": "Царево",
    "Lozenets": "Лозенец",
    "Golden Sands": "Золотые пески",
    "Albena": "Албена",
    "Balchik": "Балчик",
    "Kavarna": "Каварна",
    "Obzor": "Обзор",
    "Byala": "Бяла",
}

# ---------------------------------------------------------------------------
# Short query expansions (finance / installment queries)
# ---------------------------------------------------------------------------

SHORT_FINANCE_QUERY_EXPANSIONS: dict[str, str] = {
    "рассрочки": "какие варианты рассрочки при покупке квартиры",
    "рассрочка": "какие варианты рассрочки при покупке квартиры",
}

# ---------------------------------------------------------------------------
# HyDE system prompt (real-estate expert persona)
# ---------------------------------------------------------------------------

HYDE_SYSTEM_PROMPT = """Ты - эксперт по недвижимости.
Твоя задача: написать короткий гипотетический ответ на вопрос пользователя,
как если бы ты описывал идеальный результат поиска.

ПРАВИЛА:
1. Пиши 2-3 предложения, описывающих типичный объект недвижимости
2. Включай релевантные детали: город, тип, цена, площадь, особенности
3. Пиши на русском языке
4. НЕ задавай уточняющих вопросов
5. НЕ пиши вступление типа "Вот пример..."

Пример вопроса: "квартира у моря"
Пример ответа: "Уютная двухкомнатная квартира в Несебре, 50м², в 200 метрах от пляжа. Полностью меблирована, с балконом и видом на море. Цена 65,000 евро, поддержка 8 евро/м² в год."
"""

# ---------------------------------------------------------------------------
# Guard / filter: blocked response and query rewrite prompt
# ---------------------------------------------------------------------------

BLOCKED_RESPONSE: str = (
    "Извините, ваш запрос не может быть обработан.\n\n"
    "Я помощник по недвижимости. Пожалуйста, задайте вопрос о квартирах, "
    "домах или другой недвижимости."
)

_REWRITE_PROMPT: str = (
    "Ты — помощник по поиску недвижимости. "
    "Пользователь задал вопрос, но результаты поиска оказались нерелевантными.\n\n"
    "Переформулируй запрос так, чтобы он лучше подходил для поиска по базе недвижимости.\n"
    "Верни ТОЛЬКО переформулированный запрос, без пояснений.\n\n"
    "Оригинальный запрос: {query}"
)

# ---------------------------------------------------------------------------
# Classifier: canned responses for CHITCHAT and OFF_TOPIC query types
# ---------------------------------------------------------------------------

CHITCHAT_RESPONSES: dict[str, list[str]] = {
    "greeting": [
        "Привет! 👋 Я помогу найти недвижимость. Что вас интересует?",
        "Здравствуйте! Чем могу помочь? Ищете квартиру или дом?",
    ],
    "thanks": [
        "Пожалуйста! Если будут ещё вопросы — обращайтесь.",
        "Рад помочь! Нужно что-то ещё?",
    ],
    "bot_info": [
        "Я бот-помощник по недвижимости. Могу найти квартиры, "
        "дома, апартаменты по вашим критериям (город, бюджет, количество комнат).",
    ],
    "farewell": [
        "До свидания! Удачи в поиске! 🏠",
        "Всего доброго! Обращайтесь, если понадобится помощь.",
    ],
}

OFF_TOPIC_RESPONSES: list[str] = [
    (
        "Я специализируюсь только на недвижимости. 🏠\n\n"
        "Могу помочь найти:\n"
        "• Квартиры и апартаменты\n"
        "• Дома и виллы\n"
        "• Коммерческую недвижимость\n\n"
        "Что из этого вас интересует?"
    ),
    (
        "Извините, но я могу помочь только с вопросами о недвижимости.\n\n"
        "Напишите, например:\n"
        "• «Квартира в Несебре до 50000€»\n"
        "• «Дом у моря с 3 спальнями»\n"
        "• «Что есть в Солнечном берегу?»"
    ),
]
