apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rag

resources:
  - ../../base/namespace.yaml
  - ../../base/configmaps/postgres-init.yaml
  # Postgres
  - ../../base/postgres/pvc.yaml
  - ../../base/postgres/deployment.yaml
  - ../../base/postgres/service.yaml
  # Redis
  - ../../base/redis/pvc.yaml
  - ../../base/redis/deployment.yaml
  - ../../base/redis/service.yaml
  # Qdrant
  - ../../base/qdrant/pvc.yaml
  - ../../base/qdrant/deployment.yaml
  - ../../base/qdrant/service.yaml

commonLabels:
  app.kubernetes.io/part-of: rag-fresh
  profile: core
