"""Filter panel dialog — façade re-exporting from telegram_bot.dialogs.filter.

Split per issue #3036: move-only decomposition along aiogram-dialog grain.
All symbols remain importable from this path for backwards compatibility.
"""

from telegram_bot.dialogs.filter import (  # noqa: F401
    _ANY_OPTION,
    _FIELD_TO_RADIO_ID,
    _callback_intent_id,
    _clear_filter_dialog_state,
    _context_ids,
    _filters_to_dialog_data,
    _has_filter_value,
    _make_radio_handler,
    _make_switch_trace_handler,
    _sanitize_filter_dialog_state,
    _snapshot_filter_context,
    _start_filter_observation,
    _state_name,
    _trace_filter_output,
    _update_filter_observation,
    filter_dialog,
    get_area_data,
    get_budget_data,
    get_city_data,
    get_complex_data,
    get_floor_data,
    get_furnished_data,
    get_hub_data,
    get_promotion_data,
    get_rooms_data,
    get_view_data,
    on_apply,
    on_filter_dialog_start,
    on_radio_area,
    on_radio_budget,
    on_radio_city,
    on_radio_complex,
    on_radio_floor,
    on_radio_furnished,
    on_radio_promotion,
    on_radio_rooms,
    on_radio_view,
    on_reset,
)
